// One-tap demo inventory: one representative product per catalog category.
// Prices + images come from the Fasto reference data (scrapped_sites_data/fasto).
// Added via useStore.seedSampleInventory() so rows sync to the shop like normal adds.
export const SEED_PRODUCTS = [
  { category: 'Aata, Maida & Other Flours', name: 'Pahadi Millet Other Flour 1000g', price: 170, stock: 50, image: 'https://cdn.fasto.com.np/media/src/images/product_images/4445_product_image-kodoko-pitho-0753_1.png' },
  { category: 'Baby Care Essentials', name: 'Momeasy Baby Milk Bottle 300ml', price: 595, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/4106_momeasy-water-bottle_de797adf.png' },
  { category: 'Bakery', name: 'Ramro Royale Fruit Cake 175g', price: 130, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/7026_ramro-royale-fruit-cake-175g_cc47dbf3.jpg' },
  { category: 'Baking Essentials', name: 'Weikfield Vanilla Custard Powder 100g', price: 68, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/1801_weikfield-vanilla-custard-powder_04027dfe.png' },
  { category: 'Beauty & Personal Care', name: 'Dove Cream Serum Bar 100g', price: 125, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/892_layer-1-2026-01-05t125139910_29e68ca0.png' },
  { category: 'Beauty Appliances', name: 'Nikai N-7913 Lady Epilator', price: 1725, stock: 5, image: 'https://cdn.fasto.com.np/media/src/images/product_images/4029_whatsapp-image-2026-02-02-at-229_ec7443cd.png' },
  { category: 'Biscuits & Cookies', name: 'Parle Butter Cookies 200g', price: 60, stock: 50, image: 'https://cdn.fasto.com.np/media/src/images/product_images/71jK2Wig9PL._AC_UF10001000_QL80_.png' },
  { category: 'Breakfast & Cereals', name: 'Kelloggs Corn Flakes Original 1000g', price: 595, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/4549_layer-1-29_94509d71.png' },
  { category: 'Celebrations', name: 'Birthday Mask', price: 119, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/213198_Birthday_Mask_Blue_2.png' },
  { category: 'Chips, Cheese Balls & Snacks', name: '2PM Cheese Ball', price: 60, stock: 50, image: 'https://cdn.fasto.com.np/media/src/images/product_images/2pm_Cheese_Ball_White.png' },
  { category: 'Chiura, Bhuja and Masyura', name: 'Zoff Soya Chunks 200g', price: 140, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/5211_zoff-soya-chunks_c72aef31.png' },
  { category: 'Chocolates & Sweets', name: 'Kit Kat Chocolate Bar 42g', price: 175, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/3425_layer-1-2026-01-08t161454306_0b2a7c6a.png' },
  { category: 'Cooking Oil', name: 'Pahadi Mustard Oil 1000ml', price: 410, stock: 50, image: 'https://cdn.fasto.com.np/media/src/images/product_images/mustard_oil.png' },
  { category: 'Daal', name: 'Pahadi Masuro Daal 1000g', price: 290, stock: 50, image: 'https://cdn.fasto.com.np/media/src/images/product_images/5691_product_image-local-musuro-dal-3_7a82d73f.png' },
  { category: 'Dairy', name: 'Milkart Pasteurized Milk 900ml', price: 200, stock: 50, image: 'https://cdn.fasto.com.np/media/src/images/product_images/7285_milk-art-cow-milk_ed7dd21b.png' },
  { category: 'Deodrants & Perfumes', name: 'Nivea Male Dry Deo Roll-on 50ml', price: 265, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/3062_layer-1-89_ae8009ea.png' },
  { category: 'Detergents', name: 'Ariel Surf 500g', price: 250, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/ariel_surf_500gm.png' },
  { category: 'Dry Fruits & Nuts', name: 'Better Walnut Nuts 500g', price: 455, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/walnut.png' },
  { category: 'Female Hygiene', name: 'Zuvara Disposable Sanitary Period Panties 3pcs', price: 150, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/5622_zuvara-disposable-sanitary-m-l-period-panties_bc32f049.png' },
  { category: 'First Aid', name: 'Moov Regular Cream Pain Reliever 30g', price: 255, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/3018_layer-1-2026-01-07t154552993_51d670f0.png' },
  { category: 'Footware & Shoe Care', name: 'Cherry Wax Shoe Care 40g', price: 149, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/9e8cb0a0-cc19-4376-a1b1-814444c9d134.png' },
  { category: 'Frozen & Canned Food', name: 'McCain Veg Frozen Aloo Tikki  400g', price: 325, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/3677_layer-1-23_171d6771.png' },
  { category: 'Fruits & Vegetables', name: 'Pahadi Fresh Ginger 200g', price: 135, stock: 50, image: 'https://cdn.fasto.com.np/media/src/images/product_images/6903_6837_gingers_fc8b80b1_45129bc3.png' },
  { category: 'Geda Gudi', name: 'Pahadi Kabuli Chana 1000g', price: 270, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/kabuli_chickpeas.png' },
  { category: 'Hair Care Essentials', name: 'Dove Hairfall Rescue Shampoo 325ml', price: 390, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/871_dove-hairfall-rescue-shampoo_c6cf6de0.png' },
  { category: 'Hard Drinks & Liquors', name: '8848 Vodka 375ml', price: 1188, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/3834_8848-vodka-375ml_66b73303.png' },
  { category: 'Health Care Essentials', name: 'Dabur Hajmola Pudina Flavour', price: 95, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/6508_dabur-hajmola-pudina-flavour_1b4664ab.jpeg' },
  { category: 'Health Supplements', name: 'Poshilo Nutty Delight Satu 750gm', price: 510, stock: 5, image: 'https://cdn.fasto.com.np/media/src/images/product_images/6234_22_f27c78f0.png' },
  { category: 'Home Appliances', name: 'White Electric Mosquito Bat', price: 1160, stock: 5, image: 'https://cdn.fasto.com.np/media/src/images/product_images/4160_dual-use-electric-mosquito-swatter-400-mah-battery_02e3d81a.jpg' },
  { category: 'Home Care', name: 'Glade Touch & Fresh Combi Lavender bliss Air Fresheners 12mL', price: 232, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/temp_product_images/IMG_9114.png' },
  { category: 'Home Decor', name: 'Deer Showpiece Décor', price: 2395, stock: 5, image: 'https://cdn.fasto.com.np/media/src/images/product_images/228412_Deer_Showpiece_1.png' },
  { category: 'Ice-cream & Popsicles', name: 'Havmor Zulubar Ice Cream Candy 80ml', price: 205, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/6425_havmor-zulubarcandy-80ml_e2c4f1cf.png' },
  { category: 'Ketchups, Sauces & Pickles', name: 'Virginia Green Garden Black Olives 340g', price: 310, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/4567_layer-1-2026-01-18t121448712_ee69fec8.png' },
  { category: 'Kitchen Electronics', name: 'Toshiba 1.5 L Blender BL-T60', price: 6134, stock: 5, image: 'https://cdn.fasto.com.np/media/src/images/product_images/3949_5f9b80407fa7d50f985b23b6_toshiba-blender-bl-60phnmy-plast_vvEjxUE.png' },
  { category: 'Kitchen Essentials', name: 'Vim Tub Bar Dish Wash 500g', price: 105, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/Vim_Tub_With_Scrubbber_500gm.png' },
  { category: 'Kitchen Wares', name: 'BALTRA BVB 104 COLA BOTTLE 1000 ML', price: 1625, stock: 5, image: 'https://cdn.fasto.com.np/media/src/images/product_images/5704_cola_4ab08a14.jpg' },
  { category: 'Korean Snacks', name: 'Bibigo Chips Potato Seaweed Chips 40g', price: 455, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/6051_photo-2026-01-29-14-41-34-2_d826c4a2.jpg' },
  { category: 'Masala, Papad & Herbs', name: 'Century Chilly Flakes 50g', price: 125, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/6579_century-chilly-flakes-50g_9bf140d7.jpeg' },
  { category: 'Meat & Poultry', name: 'Urban Chicken Sausage', price: 450, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/3602_urban-chicken-sausage-2_46714819.png' },
  { category: 'Mens Grooming', name: 'Nivea Cool Kick Shaving Creams 200ml', price: 499, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/3084_nivea-cool-kick-shaving-creams-200ml_e8b3df99.png' },
  { category: 'Milk & Health Drinks', name: 'Tang Mango Flavoured Drinks 500g', price: 300, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/304fd9fe-93ed-4700-b637-c5fd3e5cc894.png' },
  { category: 'Mobile Accessories', name: 'X-AGE ConvE Play Wired Gaming Headset', price: 1800, stock: 5, image: 'https://cdn.fasto.com.np/media/src/images/product_images/4277_xgwh1product-gallery_eeab94b1.png' },
  { category: 'Namkeen & Dalmot', name: 'Bikano Tasty Peanuts 290g', price: 200, stock: 50, image: 'https://cdn.fasto.com.np/media/src/images/product_images/5920_tasty_ceca2458.jpg' },
  { category: 'Oral Care', name: 'Colgate Max Fresh Toothpaste 150g', price: 175, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/7249_colgate-max-fresh-toothpaste-150g_8e9e24fb.png' },
  { category: 'Pasta, Noodles & Soup', name: 'Wai Wai Chicken Noodles (60g *Pack of 6)', price: 120, stock: 50, image: 'https://cdn.fasto.com.np/media/src/images/product_images/6931_wai-wai-pack-of-6_23c1a29f.jpg' },
  { category: 'Pet Care', name: 'Nunbell Pet Slicker Round Brush Pet Accessories', price: 747, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/230727_Nunbell_Pet_Slicker_Round_Brush_1.png' },
  { category: 'Puja Samagri', name: 'Tia Kasturi Rose Incense Sticks DZN', price: 100, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/Tia_Rose.png' },
  { category: 'Rice', name: 'Newari Premium Shahi Pulao Long Grain Rice 5 kg', price: 995, stock: 50, image: 'https://cdn.fasto.com.np/media/src/images/product_images/4612_newari-premium-shahi-pulao-long-grain-rice-5-kg_878585fe.png' },
  { category: 'Salt & Sugar', name: 'Pahadi Sugar 500g', price: 70, stock: 50, image: 'https://cdn.fasto.com.np/media/src/images/product_images/sugar.png' },
  { category: 'Sexual Wellness', name: 'Durex Mutual Climax Condoms 3pcs', price: 232, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/4748_durex-mutual-climax-condoms-3pcs_42cf4b29.png' },
  { category: 'Skin Care Essentials', name: 'Mama Earth Ubtan Detan Sunscreen Sunscreen 50g', price: 639, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/3349_mama-earth-ubtan-detan-sunscreen-sunscreen-50g_b0fff739.png' },
  { category: 'Smokes', name: 'Surya Sleek Fine Cigarette 20pcs', price: 340, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/6267_fine_c223d678.jpeg' },
  { category: 'Soft Drinks & Juices', name: 'Pepsi Cold Drink 1500ml', price: 200, stock: 50, image: 'https://cdn.fasto.com.np/media/src/images/product_images/5175_pepsi-15-ltr_7d9a5d66.jpg' },
  { category: 'Spreads & Jams', name: 'Druk Mixed Fruit Jams 500g', price: 255, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/6101_druk-mixed-fruit-jams_156ddf25.png' },
  { category: 'Stationery', name: 'Black Binder Clip 12pcs', price: 173, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/3938_1-1-16_db26b969.png' },
  { category: 'Tea & Coffee', name: 'Tea Bag - Tokla 200g', price: 170, stock: 50, image: 'https://cdn.fasto.com.np/media/src/images/product_images/3af2965844b5d0c04837bb6475453cc4_Nq7pY0u.png' },
  { category: 'Thai Snacks', name: 'Koh-Kae Thai Sweet Chilli Coated Peanuts Snacks 80g', price: 195, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/7162_sweet-chilly_e1198f0a.jpg' },
  { category: 'Toys', name: 'Toys Bo Remote Car', price: 1250, stock: 20, image: 'https://cdn.fasto.com.np/media/src/images/product_images/3942_1-1-27_00d0e2eb.png' },
  { category: 'Travel Accessories', name: 'Straight Line With Hook', price: 635, stock: 5, image: 'https://cdn.fasto.com.np/media/src/images/product_images/342087_Neck_Pillow_Straight_Line_With_Hook_Skin1.png' },
];
